# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 송지원 (Jiwon Song)
title: Software Developer (신입)
email: woon7743@gmail.com
website: www.jsong96.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  jsong96
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
linkedin_username: https://www.linkedin.com/in/jiwon-song-a098a31b1/
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/bucky.png
about_content: | # this will include new lines to allow paragraphs
  I am a recent graduate of University of Wisconsin - Madison with a Bachelor's degree on Computer Science.
  
  열정을 가지고 백엔드의 길을 걷고 있는 신입개발자입니다

content:
  - title: Projects
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Madison Metro analysis module (Academic)
        caption: 02/2020 - 03/2020
        quote: > 
          https://github.com/jsong96/Madison_metro
        description: | 
          * 위스콘신 주 메디슨 시에서 운행중인 메트로 데이터를 사용해 메디슨 내 메트로를 visualize 해주는 python 모듈
          * 메디슨 시 내에 버스 정류장 위치, 장애인 탑승 가능 정류장 위치를 지도에 구별해서 보여주는 모듈
          * Demo: https://github.com/jsong96/Madison_metro/blob/master/demo.ipynb


      - layout: left
        title: OS-page replacement simulator (Academic)
        caption: 11/2020 - 12/2020
        quote: >
          https://github.com/jsong96/CS537/tree/main/OS-Page-replacement-simulator
        description: | # this will include new lines to allow paragraphs
          * OS 내에서 사용되는 여러 페이징 알고리즘 성능을 비교분석하는 프로그램 개발 (Linux 환경)
          * 프로그램 구조 설계 및 프론트엔드 개발
          * 사용 언어: C

      - layout: left
        title: IoT Tracking Web Application (Academic)
        caption: 01/2021 - 05/2021
        quote: >
          https://github.com/rachelhon/iot
        description: |
          * F3 Wireless 회사의 IoT Device 정보 조회를 위한 웹 어플리케이션 프로토타입 
          * F3 Wireless 회사 API를 통해 Device 정보 조회 및 유저 로그인을 위한 서버 구현
          * 사용 언어: Node js (Express)
          * DB: MongoDB

      - layout: left
        title: Full-stack Note Application (Personal)
        caption: 07/2021 - 08/2021
        quote: >
          https://github.com/jsong96/reactnotes-frontend
          https://github.com/jsong96/reactnotes-backend

        description: |
          * React와 Spring 프레임워크를 사용해 개발한 웹 노트 어플리케이션 
          * 백엔드 부분 Spring Boot와 Spring Data JPA를 사용해 노트 데이터 구현
          * 프론트엔드 부분 React와 Bootstrap를 사용해 유저 인터페이스 구현

      - layout: left
        title: Full-stack E-commerce Application (Personal)
        caption: 12/2021 - 01/2022
        quote: >
          https://github.com/jsong96/e-commerce-frontend
          https://github.com/jsong96/e-commerce-backend
        description: |
          * Angular & Spring 프레임워크를 사용해 개발한 풀스택 이커머스 어플리케이션
          * 백엔드 부분 Spring Boot, Spring Data JPA, Spring Data REST, Spring Security를 사용해 유저 로그인기능과 서버 구현
          * 프론트엔드 부분 Angular & Bootstrap를 사용해 유저 인터페이스 구현

  - title: Skill
    layout: list
    content:
      - layout: left
        title: Backend
        description: |
          * Java, Node JS (TypeScript)
          * Spring Boot, Spring Data JPA, Spring MVC, Spring Data REST, Spring Security
          * Hibernate, JPA
          * Maven
          * IntelliJ, Visual Studio Code

      - layout: left
        title: Frontend
        description: |
          * React JS, Angular JS
          * npm, yarn

  - title: Education 
    layout: list 
    content:
      - layout: left
        title: University of Wisconsin - Madison
        caption: 2015 - 2021
        sub_title: Computer Science (BA)
        description: |
          * Introduction to Algorithm 
          * Introduction to Artificial Intelligence
          * Introduction to Programming languages and Compilers
          * Introduction to Data structures
          * Introduction to Cryptography
          * Introduction to Computer Networks
          * Software Engineering
          * Data Modeling & Programming
          * Database Management Systems
          * Machine organization and programming

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Military Police
        caption: 2017 - 2019 (CheongJu, Korea)
        sub_title: Military service
        description: |
          * Served in Korean Airforce as a military police to fulfill my national duty
          * 군복무기간동안 공군에서 헌병 보직으로 근무

  - title: A Little More About Me
    layout: text
    content: | 
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - League of Legends 
      - Guitar and Bass 
      - Badger

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
