# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 송지원 (Jiwon Song)
title: Software Developer
email: woon7743@gmail.com
website: www.jsong96.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  jsong96
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: https://www.linkedin.com/in/jiwon-song-a098a31b1/
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profilepic.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a recent graduate of University of Wisconsin - Madison with Bachelor's degree on Computer Science.
  Currently pursuing a way to ...

content:
  - title: Projects
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: OS-page replacement simulator
        link: https://github.com/jsong96/CS537/tree/main/OS-Page-replacement-simulator
        description: | # this will include new lines to allow paragraphs
          This project is for ...
      
      - layout: left
        title: Madison Metro analysis module
        link: https://github.com/jsong96/Madison_metro
        description: | 
          This project is for ...

      - layout: left
        title: Full stack Note application
        link: 
        description: |
          This project is for ...

      - layout: left
        titel: Full stack E-commerce 
        link:
        description: |
          This project is for ...

  - title: Skill
    layout: list
    content:
      - layout: left
        title: Backend

      - layout: left
        title: Frontend

  - title: Programming languages
    layout: list
    content: 
      - layout: left
        title: Java

      - layout: left
        title: Python

      - layout: left
        title: C/C++

      - layout: left
        title: MySQL


  - title: Education 
    layout: list 
    content:
      - layout: left
        title: University of Wisconsin - Madison
        caption: 2015- 2021
        sub_title: Computer Science
        description: |
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | 
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - League of Legends

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
