# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 송지원 (Jiwon Song)
title: Software Developer
email: woon7743@gmail.com
website: www.jsong96.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  jsong96
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
linkedin_username: https://www.linkedin.com/in/jiwon-song-a098a31b1/
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/java.png
about_content: | # this will include new lines to allow paragraphs
  I am a recent graduate of University of Wisconsin - Madison with Bachelor's degree on Computer Science.
  Currently pursuing a way to ...

content:
  - title: Projects
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: OS-page replacement simulator
        link: https://github.com/jsong96/CS537/tree/main/OS-Page-replacement-simulator
        description: | # this will include new lines to allow paragraphs
          Built an algorithm simulator to simulate performances of three different algorithms:
          Least Recently Used, Clock, First In First Out using C language in Linux environment
          with a partner
          I was responsible for Implementing input file reading and parsing and designed the
          overall data structure workflow
          Successfully implemented the required feature and got expecting performance
          results from all three different algorithms
      
      - layout: left
        title: Madison Metro analysis module
        link: https://github.com/jsong96/Madison_metro
        description: | 
          Built a python module that analyzes the Madison metro system using the matplotlib
          and pandas library
          Was able to visualize bus trips by route, compare weekend service to weekday
          service, and visualize bus stops, distinguishing which ones are wheelchair
          accessible

      - layout: left
        title: IoT Tracking Web Application
        link:
        description: |
          Participated in a semester-long team project to build a full-stack web application
          following the traditional waterfall workflow
          I was responsible for backend developing using Node js, Express js and Mongo DB
          Successfully implemented user sign-in/up feature as well as REST API to send data
          back and forth with frontend layer

      - layout: left
        title: Full stack Note application
        link: 
        description: |
          This project is for ...

      - layout: left
        titel: Full stack E-commerce 
        link:
        description: |
          This project is for ...

  - title: Skill
    layout: list
    content:
      - layout: left
        title: Backend
        description: |
          <mark>
          * Java 
          * Spring Framework
          * Node JS
          <mark/> 

      - layout: left
        title: Frontend
        description: |
          React JS
          Angular JS

  - title: Programming languages
    layout: list
    content: 
      - layout: left
        title: Java

      - layout: left
        title: Python

      - layout: left
        title: C/C++

      - layout: left
        title: MySQL


  - title: Education 
    layout: list 
    content:
      - layout: left
        title: University of Wisconsin - Madison
        caption: 2015- 2021
        sub_title: Computer Science
        description: |
          UW - Madison

  - title: A Little More About Me
    layout: text
    content: | 
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - League of Legends
      - Guitar and Bass 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
